# This is a basic workflow to help you get started with Actions

name: Autotag-Master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get next version
        run: |
          git tag -l v* --sort=-taggerdate | tail -1 | awk -F'v' '{print $2}'
           current_version=`git tag -l v* --sort=-taggerdate | tail -1 | awk -F'v' '{print $2}'`
           echo CURRENT VERSION: $current_version
           major=`echo $current_version | cut -d'.' -f 1`
           minor=`echo $current_version | cut -d'.' -f 2`
           minor=`expr $minor + 1`
           patch=`echo $current_version | cut -d'.' -f 3`
           next_version=`echo $major.$minor.$patch`
           echo NEXT VERSION: $next_version
           echo "::set-output name=next_version::$(echo $next_version)"
        id: next_version
           
      - name: Bump version and push tag
        uses: marvinpinto/action-automatic-releases@v1.0.0
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "v${{ steps.next_version.outputs.next_version }}"
          files: '*'
